name: nirbhoy_doctor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  supabase_flutter: ^2.12.0
  flutter_riverpod: ^2.4.9
  go_router: ^17.0.1
  flutter_secure_storage: ^10.0.0
  
  # UI
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0
  
  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  intl: ^0.18.1
  flutter_launcher_icons: ^0.14.4
  in_app_update: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.3
  riverpod_annotation: ^2.3.0

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
